app2/urls.py
from django.urls import path 
from app2.views import *
app_name='aa'
urlpatterns=[
    path('pushpa/',pushpa,name='pushpa'),
    path('meghna/',meghna,name='meghna'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include

from app1.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dj/',dj,name='dj'),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dj(request):
    return render(request,'dj.html')
    

app2/views.py
from django.shortcuts import render

# Create your views here.
def pushpa(request):
    return render(request,'pushpa.html')
def meghna(request):
    return render (request,'meghna.html')
    

templates/dj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dj Tillu</h1>
        <h1>duvada jaganath</h1>
        <h2>
            <a href="{% url 'aa:meghna' %}">go to meghna</a>
        </h2>
        <h2>
            <a href="{% url 'aa:pushpa' %}">pushpa page</a>
        </h2>
    </center>
</body>
</html>

templates/meghna.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            my name is maghna
        </h1>
        <h2>
            <a href="{% url 'aa:pushpa' %}"> pushpa page</a>
        </h2>
    </center>
</body>
</html>

templates/pushpa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            party 
        </h1>
        <h1>
            taggadele
        </h1>
        <h2><a href=" { % url 'dj' %}"> travel to dj</a></h2>
        <h2><a href="{% url 'aa:meghna' %}">go to meghna html page</a></h2>
    </center>
</body>
</html>